# Generated by Django 2.1.2 on 2019-03-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourfirmApp', '0002_country_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='background_images/'),
        ),
    ]
