# Generated by Django 2.1.2 on 2019-03-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourfirmApp', '0004_auto_20190321_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
