# Generated by Django 2.1.2 on 2019-05-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourfirmApp', '0007_auto_20190418_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='better',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Выполняется', 'Выполняется'), ('Принят в обработку', 'Принят в обработку'), ('Оплачен', 'Оплачен')], max_length=100),
        ),
    ]
