# Generated by Django 2.2.2 on 2019-06-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourfirmApp', '0008_auto_20190528_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(blank=True, choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], default='Самовывоз', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оплачен', 'Оплачен'), ('Принят в обработку', 'Принят в обработку'), ('Выполняется', 'Выполняется')], max_length=100),
        ),
    ]
